[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
rustflags = [
    "-C", "link-arg=-Wl,-Tlinkall.x",
    "-C", "link-arg=-nostartfiles",
]
runner = "scripts/flash.sh"

[unstable]
build-std = ["core", "alloc"]
